theme: jekyll-theme-minimal
title: ".NET Presentations: Events in a Box!"
description: "Welcome to .NET \"Presentations in a Box.\" We have a listing of workshops and presentations YOU can use AND contribute to! Remix and share, and present at Meetups, User Groups, CodeCamps, or Conferences! Not familiar with .NET? Download open source .NET Core for any OS at http://dot.net or try it in your browser at http://try.dot.net now!"
show_downloads: true
